### PR TITLE
fix: file path finder to match paths with parenthesis

### PR DESCRIPTION
**Pull request by princejoogie**
Resolves issue #16 

image

### CODE REVIEW

**Comment by artemave** [comment]
Would be nice to add tests for those cases.

**Comment by princejoogie** [comment]
Hi @artemave i've added some tests for the paths with parenthesis and brackets

**Comment by artemave** [comment]
Nice! Lint needs fixing (you can run `make` locally to see failures), otherwise lgtm.

**Comment by princejoogie** [comment]
Hi! following up on this PR. Fixed the lint errors

**Comment by artemave** [comment]
> Hi! following up on this PR. Fixed the lint errors

Oops. Sorry, forgot about it. Just ran the build and got some test failures. Do you not get those locally?

**Comment by princejoogie** [comment]
Hi @artemave, apologies as I didn't properly setup my environment previously. Tests seems to be all passing on my end.

image

On the other hand, this specific test:
https://github.com/artemave/tmux_super_fingers/blob/6b27a8c7a2a2ed97b8dd38d18cf403b6250c42b9/tmux_super_fingers/finders/file_path_finder_test.py#L126-L142


Seems to be failing even on a freshly cloned repo.

image

**Pull request merged**
