### PR TITLE
Add python line number support

### PR DESCRIPTION
**Pull request by mareksubocz**
python stack trace has a structure of:
File "/Users/admin/main.py", line 1, in <module>

### CODE REVIEW

**Comment by artemave** [comment]
Nice one! Would you mind adding a test? It could look similar to this one: https://github.com/mareksubocz/tmux_super_fingers/blob/36a5891a9737df76eb682a3a4b960df125ed25fa/tmux_super_fingers/finders/file_path_finder_test.py#L31

**Comment by mareksubocz** [comment]
No problem. Should I open a new pull request, or how can I do this? I'm not really too familiar with pull requests workflow, just did this feature for myself and saw it was on the README checklist.

**Comment by mareksubocz** [comment]
I think this is how it's supposed to work, right? :)

**Comment by artemave** [comment]
So the test is there, but it's failing. Does it pass for you?

**Comment by mareksubocz** [comment]
It didn't, but it passes now. Basically I forgot to change a 'text' parameter in the test. Is it okay if it encapsulates one `"`, but not the other?

**Comment by artemave** [comment]
All good now - thanks!

**Pull request merged**
